name: login
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  flip_card: ^0.7.0
  mongo_dart: ^0.10.5
  http: 1.3.0
  provider: ^6.1.5
  path_provider: ^2.1.5
  timezone: ^0.10.1
  qr_code_scanner_plus: ^2.0.10+1
  image_picker: ^1.0.4
  video_player: ^2.8.1
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  socket_io_client: ^2.0.3+1
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  logger: ^2.0.2+1
  path: ^1.9.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/nomulogo.png"  

flutter:
  uses-material-design: true
  assets:
    - ../mobile-backend/.env
    - assets/images/nomulogo1.jpg
    - assets/images/ggllogo.png
    - assets/images/menu1.jpg
    - assets/images/menu2.jpg
    - assets/images/menu3.jpg
    - assets/images/mapdapitan.jpg
    - assets/images/mapdiliman.jpg
    - assets/images/mapjupiter.jpg
    - assets/images/matcha.jpg
    - assets/images/pastry.jpg
    - assets/images/dapitan.jpg
    - assets/images/jupi.png
    - assets/images/upd.png
    - assets/images/users-loyalty.png
    - assets/images/usericon.png
    - assets/images/land-layer-location.png
    - assets/images/nomutrans.png
    - assets/images/qricon.png
    - assets/images/mapicon.jpg
    - assets/images/loyaltyicon.png
    - assets/images/nomulogo.png
    - assets/images/loyaltyicon.png
    - assets/images/mapicon.jpg
    - assets/images/nomutrans.png
    - assets/images/usericon.png
    - assets/images/croissant.png
    - assets/images/coffee.png
    - assets/images/points.png
    - assets/images/matcha.jpg
    - assets/images/pastry.jpg
    - assets/images/dapitan.jpg
    - assets/images/jupi.png
    - assets/images/upd.png
    - assets/images/nomulogo1.jpg
    - assets/images/google.png
    - assets/images/manual-book.png
    - assets/images/iskor.png
    - assets/images/donut.png
    - assets/images/istetik.png
    - assets/images/load.png
    - assets/images/coffee.png
    - assets/images/donuts.png
    - assets/videos/dap.mp4
    - assets/videos/sec.mp4
    - assets/videos/third.mp4
    - assets/images/nomudisplay.jpg
    - assets/images/nomudisplay2.jpg
    - assets/images/nomudisplay3.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/static/Montserrat-Regular.ttf
        - asset: assets/fonts/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Montserrat-Bold.ttf
          weight: 700

